name: Backend Continuous Integration

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/ci-be.yml'
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/ci-be.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    concurrency:
      group: pr-${{ github.event.pull_request.number }}-be
      cancel-in-progress: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile.production
        push: false