name: Backend Continuous Integration

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/ci-be.yml'
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/ci-be.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Dockerfile.production
        push: false