name: Frontend Continuous Integration

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/ci-fe.yml'
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/ci-fe.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        working-directory: ./frontend
    concurrency:
      group: pr-${{ github.event.pull_request.number }}-fe
      cancel-in-progress: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      working-directory: ${{env.working-directory}}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
      working-directory: ${{env.working-directory}}

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ${{env.working-directory}}

    - name: Lint
      run: yarn lint
      working-directory: ${{env.working-directory}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      working-directory: ${{env.working-directory}}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile.production
        push: false
      working-directory: ${{env.working-directory}}